---
# install_openmediavault_on_debian/tasks/main.yml

- name: 'Setup the Openmediavault package repository'
  include: repository.yml
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version == "11"'

- name: 'Install the Openmediavault packages'
  include: package_installation.yml
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version == "11"'

- name: 'Run omv-confdbadm populate (and create a dummy file to make this idempotent'
  shell:
    cmd: 'omv-confdbadm populate && touch /etc/openmediavault/.ansible_executed_omv-confdbadm_populate'
    creates: '/etc/openmediavault/.ansible_executed_omv-confdbadm_populate'
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version == "11"'

- name: 'Set the admin user password'
  user:
    name: 'admin'
    password: "{{ admin_password_hash }}"
  no_log: 'true'
  when:
    - 'ansible_distribution == "Debian"'
    - 'ansible_distribution_major_version == "11"'
    - 'admin_password_hash is defined'
